---
- name: GitLab DB migration and DB host switching
  hosts: '{{ hostname }}'
  become: true
  become_user: root
  vars:
    aws_access_key_id: "{{ minio_access_key | default('accesskey') }}"
    aws_secret_access_key: "{{ minio_secret_key | default('secretkey') }}"  
    db_host: "{{ hostvars['haproxy'].ansible_host }}"
    db_port: 6432

  tasks:
    - name: DB migration with retry
      shell: |
        set -e
        gitlab-rake gitlab:db:configure
      register: db_migration_result
      retries: 3
      delay: 30
      until: db_migration_result.rc == 0 and
            ('cannot execute CREATE SCHEMA in a read-only transaction' not in db_migration_result.stdout)
      failed_when: db_migration_result.rc != 0 and
                  ('cannot execute CREATE SCHEMA in a read-only transaction' in db_migration_result.stdout)
      when: inventory_hostname == (groups['rails'] | sort | first)

    - name: Update gitlab.rb after DB migration 
      template:
        src: templates/gitlab.rb.j2
        dest: /etc/gitlab/gitlab.rb
        owner: root
        group: root
        mode: '0600'
      when: inventory_hostname == (groups['rails'] | sort) | first

    - name: Clean updated gitlab.rb after DB migration 
      shell: |
        grep -vE '^\s*#|^\s*$' /etc/gitlab/gitlab.rb > /tmp/gitlab.rb.cleaned
        mv /tmp/gitlab.rb.cleaned /etc/gitlab/gitlab.rb
        chmod 0600 /etc/gitlab/gitlab.rb
      when: inventory_hostname == (groups['rails'] | sort) | first
