---
- name: Configure PgBouncer and check connectivity
  hosts: '{{ hostname }}'
  become: true  
  become_user: root
  tasks:
    - name: Create .pgpass if PgBouncer node
      shell: |
        echo -e "{{ pgbouncer_password | default('pgbouncerpassword') }}\n{{ pgbouncer_password | default('pgbouncerpassword') }}" | sudo gitlab-ctl write-pgpass \
          --host 127.0.0.1 \
          --database pgbouncer \
          --user pgbouncer \
          --hostuser gitlab-consul
        sudo gitlab-ctl hup pgbouncer
      when: inventory_hostname.startswith('pgbouncer')


