---
- name: Setup Praefect database
  hosts: '{{ hostname }}'
  become: true

  tasks:
    - name: Setup Praefect DB user
      shell: |
        /opt/gitlab/embedded/bin/psql -U gitlab-psql -h "127.0.0.1" -d template1 <<EOF
        CREATE ROLE praefect WITH LOGIN CREATEDB PASSWORD 'praefectpassword';
        EOF
      when: inventory_hostname.startswith('praefect_db')

    - name: Setup Praefect DB
      shell: |
        PGPASSWORD=praefectpassword /opt/gitlab/embedded/bin/psql -U praefect -h "127.0.0.1" -d template1 <<EOF
        CREATE DATABASE praefect_production WITH ENCODING=UTF8;
        EOF
      when: inventory_hostname.startswith('praefect_db')
