---
- name: Install Gitlab External HA LB with self-signed cert
  hosts: "{{ hostname }}"
  become: true
  become_user: root 
  vars:
    domain: mygitlab.idtice.com
    cert_path: /etc/ssl/certs/selfsigned.crt
    key_path: /etc/ssl/private/selfsigned.key
    combined_pem_path: /etc/ssl/certs/haproxy_cert.pem

  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        name: [openssl, haproxy]
        state: latest
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Generate self-signed SSL certificate and private key
      shell: |
        openssl req -x509 -nodes -days 365 \
          -newkey rsa:2048 \
          -keyout {{ key_path }} \
          -out {{ cert_path }} \
          -subj "/C=KR/ST=Seoul/L=Seoul/O=MyCompany/OU=IT/CN={{ domain }}"
      args:
        creates: "{{ cert_path }}"

    - name: Combine certificate and key into HAProxy-compatible PEM file
      shell: |
        cat {{ cert_path }} {{ key_path }} > {{ combined_pem_path }}
      args:
        creates: "{{ combined_pem_path }}"

    - name: Copy internal HAProxy configuration
      copy:
        src: templates/external-haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: '0644'

    - name: Start and enable HAProxy service
      ansible.builtin.systemd:
        name: haproxy
        state: restarted
        enabled: true
