---
- name: Install GitLab HA
  hosts: '{{ hostname }}'
  become: true
  become_user: root
  serial: 1 
  vars:
    aws_access_key_id: "{{ minio_access_key | default('accesskey') }}"
    aws_secret_access_key: "{{ minio_secret_key | default('secretkey') }}"
  tasks:
    - name: Install Pre requsites packages for GitLab
      ansible.builtin.apt:
        name: '{{ item }}'
        state: latest
      with_items:
        - curl 
        - openssh-server
        - ca-certificates
        - tzdata
        - perl
        - unzip
        - software-properties-common
      when: ansible_os_family == "Debian" 

    - name: Add GitLab package repository
      ansible.builtin.shell: "curl -s https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh | sudo bash"
      args:
        creates: /etc/apt/sources.list.d/gitlab_gitlab-ee.list
  
    - name: Temporarily disable swap
      ansible.builtin.command: swapoff -a
      become: true
    
    - name: Install GitLab
      ansible.builtin.apt:
        name: "gitlab-ee=17.10.1-ee.0"
        state: present

    - name: Set DB host/port to Patroni leader
      set_fact:
        db_host: "{{ patroni_leader_ip | default('10.0.10.13') }}"
        db_port: 5432

    - name: Update /etc/gitlab/gitlab.rb
      ansible.builtin.template:
        src: templates/gitlab.rb.j2
        dest: /etc/gitlab/gitlab.rb
        owner: root
        group: root
        mode: '0600'
      register: template

    - name: Configure GitLab
      ansible.builtin.shell: gitlab-ctl reconfigure
      register: reconfigure_output
      ignore_errors: yes
      retries: 3
      delay: 30

    - name: DB migration
      ansible.builtin.shell: gitlab-rake gitlab:db:configure

    - name: Revert db connection to PgBouncer
      set_fact:
        db_host: "{{ hostvars['haproxy'].ansible_host }}"
        db_port: 6432

    - name: Update gitlab.rb configuration
      template:
        src: templates/gitlab.rb.j2
        dest: /etc/gitlab/gitlab.rb
        owner: root
        group: root
        mode: '0600'
      register: template2

    - name: Configure GitLab Again
      ansible.builtin.shell: gitlab-ctl reconfigure
      register: reconfigure2_output
      ignore_errors: yes
      retries: 3
      delay: 30

    - name: Skip auto reconfigure
      file:
        path: /etc/gitlab/skip-auto-reconfigure
        state: touch

    - name: Check GitLab status
      command: "/opt/gitlab/bin/gitlab-ctl status"
      register: status_output

    - name: Run gitlab:check
      ansible.builtin.shell: gitlab-rake gitlab:check
      when: inventory_hostname == (groups['rails'] | sort) | last
      register: gitlab_check_output
    
    - name: Show reconfigure output
      debug:
        var: reconfigure_output.stdout_lines

    - name: Show reconfigure2 output
      debug:
        var: reconfigure2_output.stdout_lines

    - name: Show status output
      debug:
        var: status_output.stdout_lines

    - name: Show gitlab:check output
      ansible.builtin.debug:
        var: gitlab_check_output.stdout_lines 
      when: inventory_hostname == (groups['rails'] | sort) | last 