---
- name: Install GitLab HA
  hosts: '{{ hostname }}'
  become: true
  become_user: root
  serial: '{{ serial_number | default("1") }}'

  tasks:
    - name: Install Pre requsites packages for GitLab
      ansible.builtin.apt:
        name: '{{ item }}'
        state: latest
      with_items:
        - curl 
        - openssh-server
        - ca-certificates
        - tzdata
        - perl
        - unzip
        - software-properties-common
      when: ansible_os_family == "Debian" 

    - name: Add GitLab package repository
      ansible.builtin.shell: "curl -s https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh | sudo bash"
      args:
        creates: /etc/apt/sources.list.d/gitlab_gitlab-ee.list

    - name: Ensure 'Match User git' block is configured
      ansible.builtin.blockinfile:
        path: /etc/ssh/sshd_config
        marker: "# {mark} ANSIBLE MANAGED BLOCK - GitLab Fast SSH Key Lookup"
        block: |
          Match User git
            AuthorizedKeysCommand /opt/gitlab/embedded/service/gitlab-shell/bin/gitlab-shell-authorized-keys-check git %u %k
            AuthorizedKeysCommandUser git
          Match all
        create: yes
        state: present
 
    - name: Validate sshd config syntax
      ansible.builtin.command: sshd -t
      become: true

    - name: Reload SSH service
      ansible.builtin.service:
        name: ssh
        state: reloaded
      become: true
  
    - name: Temporarily disable swap
      ansible.builtin.command: swapoff -a
      become: true
    
    - name: Install GitLab
      ansible.builtin.apt:
        name: "gitlab-ee=17.10.1-ee.0"
        state: present

    - name: Update /etc/gitlab/gitlab.rb
      ansible.builtin.template:
        src: templates/gitlab.rb.j2
        dest: /etc/gitlab/gitlab.rb
        owner: root
        group: root
        mode: '0600'
      register: template

    - name: Configure GitLab
      ansible.builtin.shell: "/opt/gitlab/bin/gitlab-ctl reconfigure"
      when: template.changed
      register: reconfigure_output

    - name: Check GitLab status
      command: "/opt/gitlab/bin/gitlab-ctl status"
      register: status_output

    - debug:
        var: reconfigure_output.stdout_lines

    - debug:
        var: status_output.stdout_lines

    # sudo /opt/gitlab/embedded/bin/consul members