---
- name: Install GitLab HA
  hosts: '{{ hostname }}'
  become: true
  become_user: root
  serial: '{{ serial_number | default("1") }}'

  tasks:
    - name: Install Pre requsites packages for GitLab
      ansible.builtin.apt:
        name: '{{ item }}'
        state: latest
      with_items:
        - curl 
        - openssh-server
        - ca-certificates
        - tzdata
        - perl
        - unzip
        - software-properties-common
      when: ansible_os_family == "Debian" 

    - name: Add GitLab package repository
      ansible.builtin.shell: "curl -s https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh | sudo bash"
      args:
        creates: /etc/apt/sources.list.d/gitlab_gitlab-ee.list

    - name: Ensure /etc/ssh_static exists
      ansible.builtin.file:
        path: /etc/ssh_static
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy SSH keys to /etc/ssh_static
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/etc/ssh_static/"
        owner: root
        group: root
        mode: preserve
        remote_src: yes
      with_fileglob:
        - /etc/ssh/ssh_host_*_key*

    - name: Ensure HostKey entries exist in sshd_config
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        line: "HostKey /etc/ssh_static/{{ item }}"
        state: present
        create: yes
      loop:
        - ssh_host_rsa_key
        - ssh_host_dsa_key
        - ssh_host_ecdsa_key
        - ssh_host_ed25519_key

    - name: Ensure 'Match User git' block is configured
      ansible.builtin.blockinfile:
        path: /etc/ssh/sshd_config
        marker: "# {mark} ANSIBLE MANAGED BLOCK - GitLab Fast SSH Key Lookup"
        block: |
          Match User git
            AuthorizedKeysCommand /opt/gitlab/embedded/service/gitlab-shell/bin/gitlab-shell-authorized-keys-check git %u %k
            AuthorizedKeysCommandUser git
          Match all
        create: yes
        state: present

    - name: Temporarily disable swap
      ansible.builtin.command: swapoff -a
      become: true
    
    - name: Reload SSH service
      ansible.builtin.service:
        name: ssh
        state: reloaded

    - name: Install GitLab
      ansible.builtin.apt:
        name: "gitlab-ee=17.10.1-ee.0"
        state: present

    - name: Update /etc/gitlab/gitlab.rb
      ansible.builtin.template:
        src: templates/gitlab.rb.j2
        dest: /etc/gitlab/gitlab.rb
        owner: root
        group: root
        mode: '0600'
      register: template

    - name: Configure GitLab
      ansible.builtin.shell: "/opt/gitlab/bin/gitlab-ctl reconfigure"
      when: template.changed
      register: reconfigure_output

    - name: Check GitLab status
      command: "/opt/gitlab/bin/gitlab-ctl status"
      register: status_output

    - debug:
        var: reconfigure_output.stdout_lines

    - debug:
        var: status_output.stdout_lines

    # sudo /opt/gitlab/embedded/bin/consul members