--- 
- name: Install Gitlab External HA LB
  hosts: "{{ hostname }}"
  become: true
  become_user: root 
  vars:
    domain: mygitlab.idtice.com
    cert_path: /etc/ssl/certs/selfsigned.crt
    key_path: /etc/ssl/private/selfsigned.key
    combined_pem_path: /etc/ssl/certs/haproxy_cert.pem

  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        name: [openssl, haproxy]
        state: latest
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Generate a self-signed certificate
      openssl_certificate:
        path: "{{ cert_path }}"
        privatekey_path: "{{ key_path }}"
        common_name: "{{ domain }}"
        provider: selfsigned
        days: 365
        subject:
          locality_name: "Seoul"
          organization_name: "My Company"
          organizational_unit_name: "IT"
      notify: Combine cert and key

    - name: Combine certificate and key into HAProxy-compatible PEM file
      shell: |
        cat {{ cert_path }} {{ key_path }} > {{ combined_pem_path }}
      args:
        creates: "{{ combined_pem_path }}"

    - name: Copy internal HAProxy configuration
      copy:
        src: templates/external-haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: '0644'

    - name: Start and enable HAProxy service
      ansible.builtin.systemd:
        name: haproxy
        state: restarted
        enabled: true

  handlers:
    - name: Combine cert and key
      shell: |
        cat {{ cert_path }} {{ key_path }} > {{ combined_pem_path }}
      notify: Restart haproxy

    - name: Restart haproxy
      ansible.builtin.systemd:
        name: haproxy
        state: restarted
